### ISSUE TITLE
Поле с результатом вычисления не меняется если ввести чтото

### ISSUE THREAD

**Issue by npac** [slovn1k/SinglePageApp#5]
Почему результат виден только  в placeholder?

**Comment by slovn1k** [comment]
А где еще результат должен быть виден??? Мне исправить в версий с angular
ошибки???

2016-06-28 16:36 GMT+03:00 pcapcanari notifications@github.com:

**Comment by npac** [comment]
Для результата не обязательно использовать input  элемент. Можно просто отображать значение как <h1>{{result}}</h1> 

Исправляй пожалуйста
