### ISSUE TITLE
Отсутсвует unit test

### ISSUE THREAD

**Issue by npac** [slovn1k/SinglePageApp#6]
каждый уважающий себя программист  должен писать Unit testы 
https://docs.angularjs.org/guide/unit-testing

**Comment by slovn1k** [comment]
я тесты не писал никогда, мне написать??

2016-06-28 16:38 GMT+03:00 pcapcanari notifications@github.com:

**Comment by npac** [comment]
Самое время попробовать и разобраться. Без них ни как.
